version: '3.1'
services:
  ngnix-ui:
    image: 'nginx'
    container_name: ngnix-ui
    ports:
      - '8081:80'
    volumes:
      - './nginx-ui/html:/usr/share/nginx/html'
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 172.21.0.1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  netcore-api:
    image: resulguldibi/netcore-api
    container_name: netcore-api
    restart: always
    depends_on:
      - kafka
    links:
      - kafka
    ports:
      - '8080:8080'
  go-service:
    image: resulguldibi/full-stack-sample/go-service
    container_name: go-service
    restart: always
    depends_on:
      - kafka
      - cassandra
    links:
      - kafka
      - cassandra
    ports:
      - '8083:8080'
  postgres:
    image: 'postgres:11'
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'my_dbdata:/var/lib/postgresql/data'
    environment:         
      POSTGRES_PASSWORD: pwd123
      POSTGRES_USER: postgresuser
  cassandra:
    image: cassandra
    container_name: cassandra
    restart: always
    ports:
      - '9042:9042'
    environment:
      CASSANDRA_CLUSTER_NAME: my_cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_DC: my_datacenter
  postgres-api:
    image: resulguldibi/postgres-api
    container_name: postgres-api
    restart: always
    depends_on:
      - cassandra
      - postgres
    links:
      - cassandra
      - postgres
    ports:
      - '8082:8080'
volumes:
    my_dbdata:
      
