version: '3.1'

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        ports:
            - 2181:2181
    consumer-dispatcher:
        image: resulguldibi/full-stack-sample/go-service
        container_name: go-service
        restart: always
        depends_on:
            - kafka
        links:
            - kafka
        ports: 
            - 8080:8080
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 172.21.0.1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

